[package]
name = "maos"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "maos"
path = "src/main.rs"

[dependencies]
maos-core = { path = "../maos-core" }
clap = { workspace = true }
tokio = { workspace = true, features = ["io-std", "io-util", "time", "macros", "rt"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
bytes = "1.5"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
criterion = "0.5"

[[bench]]
name = "io_bench"
harness = false