# Cargo configuration for MAOS

[env]
# Test profiles for different environments
# Set MAOS_TEST_MODE to control test behavior:
#   - "fast" (default): Quick local dev, minimal fuzzing
#   - "thorough": Balanced CI testing  
#   - "comprehensive": Full security validation

# Example usage:
#   MAOS_TEST_MODE=thorough cargo test
#   PROPTEST_CASES=1000 cargo test --test security_fuzzing

[alias]
# Quick test aliases for different modes
test-fast = "test --package maos"
test-thorough = "test --package maos -- --include-ignored"
test-security = "test --package maos --test security_fuzzing -- --ignored"
test-unit = "test --package maos --lib"
test-integration = "test --package maos --tests"

# Benchmark aliases
bench-memory = "bench --package maos --bench memory_bench"

[profile.test]
# Optimize test builds for faster compilation
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 256
rpath = false

[profile.bench]
# Match release profile for accurate real-world measurements
opt-level = "z"  # Size optimization to match release
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"  # Full LTO to match release
incremental = false
codegen-units = 1
rpath = false
