openapi: 3.0.0
info:
  title: MAOS MCP Server API
  description: OpenAPI spec for scaffolding MAOS MCP server with Agenterra - represents the 3 core MCP tools
  version: 1.0.0

paths:
  /orchestrate:
    post:
      operationId: orchestrate
      summary: Start a multi-agent orchestration session
      description: |
        Initiates an orchestration session where the Orchestrator coordinates
        multiple agents through the Claude Code Agent to accomplish a goal.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                objective:
                  type: string
                  description: High-level goal to accomplish
                agents:
                  type: array
                  description: Initial agents to consider (optional)
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        description: Agent role (architect, engineer, qa, etc.)
                      task:
                        type: string
                        description: Specific task for this agent
                strategy:
                  type: string
                  enum: [parallel, sequential, adaptive]
                  default: adaptive
                  description: Execution strategy for orchestration
              required:
                - objective
      responses:
        '200':
          description: Orchestration session started
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    description: Unique session identifier
                  status:
                    type: string
                    enum: [started, planning, executing]
                  message:
                    type: string
                    description: Initial status message

  /session-status:
    get:
      operationId: sessionStatus
      summary: Get the current status of an orchestration session
      description: |
        Returns the current state of an orchestration session including
        phase progress and agent activity.
      parameters:
        - name: session_id
          in: query
          required: true
          schema:
            type: string
          description: Session identifier
        - name: include_agents
          in: query
          required: false
          schema:
            type: boolean
            default: true
          description: Include detailed agent information
      responses:
        '200':
          description: Session status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                  objective:
                    type: string
                  state:
                    type: string
                    enum: [planning, executing, completed, failed]
                  current_phase:
                    type: object
                    properties:
                      number:
                        type: integer
                      name:
                        type: string
                      agents:
                        type: array
                        items:
                          type: object
                          properties:
                            role:
                              type: string
                            task:
                              type: string
                            status:
                              type: string
                  progress:
                    type: object
                    properties:
                      phases_completed:
                        type: integer
                      current_phase:
                        type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time

  /list-roles:
    get:
      operationId: listRoles
      summary: List available agent roles
      description: |
        Returns the list of available agent roles that can be used
        in orchestration sessions.
      parameters:
        - name: include_descriptions
          in: query
          required: false
          schema:
            type: boolean
            default: true
          description: Include role descriptions and capabilities
      responses:
        '200':
          description: List of available roles
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Role identifier (e.g., architect, engineer)
                        description:
                          type: string
                          description: Brief description of the role
                        capabilities:
                          type: array
                          items:
                            type: string
                          description: List of capabilities for this role

  # SSE endpoint for streaming orchestrator output
  /sessions/{session_id}/stream:
    get:
      operationId: streamSession
      summary: Stream orchestrator output via Server-Sent Events
      description: |
        Provides real-time streaming of orchestrator output and progress
        updates via Server-Sent Events (SSE).
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: Session identifier to stream
      responses:
        '200':
          description: SSE stream established
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Events stream

components:
  schemas:
    SessionInfo:
      type: object
      properties:
        session_id:
          type: string
        objective:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
    
    AgentRole:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        capabilities:
          type: array
          items:
            type: string