name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  MAOS_TEST_PROFILE: ci  # Use CI test profile with maximum thoroughness

jobs:
  # Cross-platform CI pipeline - runs full CI on all platforms
  ci:
    name: CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2

      # Set test profile for CI (all platforms)
      - name: Setup Test Environment (Linux/macOS)
        if: runner.os != 'Windows'
        run: echo "MAOS_TEST_PROFILE=ci" >> $GITHUB_ENV
        
      - name: Setup Test Environment (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "MAOS_TEST_PROFILE=ci" >> $env:GITHUB_ENV
          # Windows can't process bash case statements, so set test values explicitly
          echo "MAOS_TEST_SECURITY_PROPTEST_CASES=1000" >> $env:GITHUB_ENV
          echo "MAOS_TEST_E2E_TIMEOUT_MS=120000" >> $env:GITHUB_ENV
          echo "MAOS_TEST_BENCHMARK_ITERATIONS=1000" >> $env:GITHUB_ENV
      
      # Install dependencies
      - name: Install development dependencies
        run: just install-deps
      
      # Validate environment
      - name: Validate stack environment
        run: just validate-stack
      
      # Run full CI pipeline
      - name: Run CI pipeline
        run: just ci