name: Release Drafter

on:
  push:
    branches:
      - main
  # Allow manual trigger to update draft
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        # Only run on main branch pushes or manual triggers
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}